[workspace]

members = ["day01", "day02", "day03", "day04", "day05", "meta"]
resolver = "2"


[workspace.dependencies]
aoc-traits = { git = "https://github.com/dkales/adventofcode2023-leaderboard", rev = "16aac98471cab02bb856980dbc469de4b0a7f657" }
